#!/bin/bash -e

POSTGRES_HOST=${POSTGRES_HOST:-postgres}
POSTGRES_PORT=${POSTGRES_PORT:-5432}
POSTGRES_USER=${POSTGRES_USER:-pherald}
POSTGRES_DB_NAME=${POSTGRES_DB_NAME:-pherald}
# you should set password in the environment variable, do notuse this example pasword
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-VGh1IEphbiAyMSAxNDo1NzowOSBDRVQgMjAxNgo}
POSTGRES_DEPLOY_DATABASE=${POSTGRES_DEPLOY_DATABASE:-yes}
HERALD_PORT=8081

echo "$POSTGRES_PASSWORD" > /etc/pherald/passfile

if [[ -v $POSTG ]]; then
  #statements
fi
psql -h $POSTGRES_PORT -d $POSTGRES_DB_NAME -U $POSTGRES_USER <<EOF
DO
$body$
BEGIN
   IF NOT EXISTS (
      SELECT *
      FROM   pg_catalog.pg_user
      WHERE  usename = '${POSTGRES_USER}') THEN

      CREATE ROLE ${POSTGRES_USER} LOGIN PASSWORD "${POSTGRES_PASSWORD}"
        NOSUPERUSER INHERIT NOCREATEDB
        NOCREATEROLE NOREPLICATION ;
   END IF;
END
$body$;

CREATE DATABASE "${POSTGRES_DB_NAME}" WITH OWNER = #{POSTGRES_USER}
  ENCODING = 'UTF8'
  TABLESPACE = pg_default;
EOF
